# Generated by Django 5.2.6 on 2025-11-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo576',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=15)),
                ('ejercicio', models.PositiveIntegerField()),
                ('periodo', models.CharField(max_length=5)),
                ('hecho_imponible', models.CharField(choices=[('1', 'Primera matriculación definitiva'), ('2', 'Circulación o utilización en España'), ('3', 'Modificación de características técnicas'), ('4', 'Introducción desde Canarias/Baleares'), ('5', 'Renuncia a beneficios fiscales')], max_length=2)),
                ('medio_transporte_nuevo', models.BooleanField(default=False)),
                ('medio_transporte_usado', models.BooleanField(default=False)),
                ('fecha_prueba_servicio', models.DateField(blank=True, null=True)),
                ('kilometros', models.IntegerField(blank=True, null=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo_tipo', models.CharField(max_length=50)),
                ('numero_serie', models.CharField(max_length=50)),
                ('motor', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('electrico', 'Electrico'), ('otros', 'Otros')], max_length=10)),
                ('cilindrada', models.IntegerField(blank=True, null=True)),
                ('emisiones_co2', models.IntegerField(blank=True, null=True)),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deduccion_lineal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cuota_ingresar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_presentacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
