# Generated by Django 5.2.6 on 2025-11-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo576',
            old_name='ejercicio',
            new_name='matricula',
        ),
    ]
