# Generated by Django 5.2.6 on 2025-11-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_rename_ejercicio_modelo576_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo576',
            name='deduccion_lineal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
