# Generated by Django 5.2.7 on 2025-10-07 14:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Declaracion349',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.PositiveIntegerField()),
                ('periodo', models.CharField(max_length=20)),
                ('presentado_por', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_operadores', models.PositiveIntegerField(default=0)),
                ('total_base_imponible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='SujetoPasivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('pueblo', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('pais', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperadorIntracomunitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif_operador', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=3)),
                ('clave', models.CharField(choices=[('A', 'Entrega de bienes'), ('B', 'Prestación de servicios'), ('C', 'Operación triangular')], max_length=2)),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=18)),
                ('observaciones', models.CharField(blank=True, max_length=300, null=True)),
                ('declaracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadores', to='taxes.declaracion349')),
            ],
        ),
        migrations.AddField(
            model_name='declaracion349',
            name='sujeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaraciones', to='taxes.sujetopasivo'),
        ),
    ]
