# Generated by Django 5.2.6 on 2025-09-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo146',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('estado_civil', models.CharField(max_length=20)),
                ('hijos', models.IntegerField(default=0)),
                ('fecha_presentacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
