# Generated by Django 5.2.6 on 2025-09-30 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_IAW', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo146',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='modelo146',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='modelo146',
            name='fecha_presentacion',
        ),
        migrations.RemoveField(
            model_name='modelo146',
            name='hijos',
        ),
        migrations.AddField(
            model_name='modelo146',
            name='codigo_postal',
            field=models.CharField(default='46950', max_length=10),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='ejercicio',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='escalera',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='lugar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='piso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='primer_apellido',
            field=models.CharField(default='SinApellido', max_length=100),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='puerta',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='representante_codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='representante_municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='representante_nif',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='representante_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='representante_numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='representante_provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='representante_via_publica',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='telefono1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='telefono2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='via_publica',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='modelo146',
            name='nif',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='modelo146',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='EntidadPagadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif_pagador', models.CharField(max_length=9)),
                ('razon_social', models.CharField(max_length=200)),
                ('importe_anual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('modelo146', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagadores', to='app_IAW.modelo146')),
            ],
        ),
    ]
