# Generated by Django 5.2.6 on 2025-10-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_IAW', '0002_remove_modelo146_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo146',
            name='importe_bruto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='importe_neto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='importe_retencion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='modelo146',
            name='tipo_irpf',
            field=models.DecimalField(decimal_places=2, default=19.0, max_digits=5),
        ),
    ]
