# Generated by Django 5.2.6 on 2025-11-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_IAW', '0003_modelo146_importe_bruto_modelo146_importe_neto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo146',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='modelo146',
            name='ejercicio',
        ),
        migrations.RemoveField(
            model_name='modelo146',
            name='escalera',
        ),
        migrations.RemoveField(
            model_name='modelo146',
            name='piso',
        ),
        migrations.RemoveField(
            model_name='modelo146',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='modelo146',
            name='puerta',
        ),
        migrations.RemoveField(
            model_name='modelo146',
            name='telefono2',
        ),
        migrations.AlterField(
            model_name='modelo146',
            name='primer_apellido',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
