# Generated by Django 5.2.7 on 2025-11-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impuesto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracionirpf',
            name='renta_neta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
