# Generated by Django 5.2.7 on 2025-11-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracionIRPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif_cliente', models.CharField(max_length=20)),
                ('nif_empresa', models.CharField(max_length=20)),
                ('numero_impuesto', models.CharField(max_length=50)),
                ('sueldo_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingresos_alquileres', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingresos_capital', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ganancias_patrimoniales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cotizaciones_ss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('otros_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_a_recaudar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
